### ISSUE TITLE
Buttons are located above the text

### ISSUE THREAD

**Issue by ogheo** [sprice/videojs-resume#10]
Hi,

I have a question, at the moment buttons are located above the text, is this normal or it is a bug?

http://s22.postimg.org/53ab36fvl/continue.png - video.js 5.8.0

PS: it seems to be a bug cause I tested with video.js 5.5.0 and buttons were located after the text.

http://s24.postimg.org/l0bvpyupx/continue5_5_0.png  - video.js 5.5.0

**Comment by alexgarrettsmith** [comment]
I just noticed this too. Can be fixed with CSS, but a little hacky.

**Comment by ntamblyn** [comment]
@alexgarrett any chance you can provide me with the css changes please

**Comment by pvenakis** [comment]
This issue is fixed if you locate the following:
`innerHTML: '\n        <p>' + this.options_.title + '</p>\n      '`
and remove the `<p>` tags:
`innerHTML: '\n        ' + this.options_.title + '\n      '`
