### ISSUE TITLE
Dynamic events

### ISSUE THREAD

**Issue by Krato** [sprice/videojs-resume#14]
Hi, thank you for your plugin.

I have a problem. I'm changing source of video dynamic, but I want also to add this plugin. I can be able to set resume for each video. But, how can I show again the resume popup again without destroy the video?

Thanks!

**Comment by Krato** [comment]
nothing?

**Comment by sprice** [comment]
@Krato any chance you could post a super simple test case `.html` file of what you are describing so that I can understand the issue better? Or maybe a link to an example where you are doing this dynamic source changing?
