### ISSUE TITLE
videojs-resume data is removed from local storage when paused by click on video

### ISSUE THREAD

**Issue by cplaiasu** [sprice/videojs-resume#2]
videojs-resume data is removed from local storage when paused by click on video
![image](https://cloud.githubusercontent.com/assets/7574389/11487921/4e02db34-97cb-11e5-96f0-0d14e26db218.png)

**Comment by sprice** [comment]
Can you provide some info about your browser. Are you using the demo site?

[On the demo site](https://sprice.github.io/videojs-resume/), I can play and pause a video by clicking on the video in Chrome 46 on El Capitan and localstorage seems fine.

![videojs-resume-pause-localstorage](https://cloud.githubusercontent.com/assets/165397/11495483/5f242d9c-97c0-11e5-9486-80f212bc6f21.gif)

**Comment by cplaiasu** [comment]
Works just fine now, thanks!
Yesterday that local storage issue was in same Chrome 46 on El Capitan and Chrome 47 un Ubuntu 15.10

**Comment by sprice** [comment]
I did some work on this yesterday removing the jQuery dependency. That may have solved the bug. Thanks!
