### ISSUE TITLE
Bugs when press spacebar keyboard.

### ISSUE THREAD

**Issue by andiksetyawan** [sprice/videojs-resume#5]
Bugs when press spacebar keyboard. 

When i press spacebar (in example) . video is load current time. 
How to disable spacebar event ??

**Comment by andiksetyawan** [comment]
Yeah fixed.
Just delete event spacebar and enter in video.js line 2857 : check : 
Button.prototype.handleKeyPress = function handleKeyPress(event) {
    /\* Check for space bar (32) or enter (13) keys
    if (event.which === 32 || event.which === 13) {
      event.preventDefault();
      this.handleClick(event);
    }*/
  };

**Comment by sprice** [comment]
Hacking video.js isn't the solution here (you really shouldn't ever have to change the main video.js source file). I've made a fix to this plugin and pushed a new release.

**Comment by setyawanandik** [comment]
Great !!!! :+1:

**Comment by andiksetyawan** [comment]
Not fix, then not work event pause play..Code above really fix with me and combine with hot keys plugin its great solution.

**Comment by sprice** [comment]
@setyawanandik sorry, the example wasn't using the latest version. I've updated it now and the space bar works (mostly) as expected. But it seems there is a [bug](https://github.com/videojs/video.js/issues/2669) with `video.js` where the space bar won't work until the video has already been paused after playback has begun.
