### ISSUE TITLE
videojs-resume & composer

### ISSUE THREAD

**Issue by ogheo** [sprice/videojs-resume#6]
Is this plugin available with composer? if not, please make it available.

tnx.

**Comment by sprice** [comment]
I'm assuming you mean a `composer.json` file for PHP packages. Is that right? I'm not too familiar with it but I can work on a pull request and ask you to take a look at it. Does that work?

**Comment by ogheo** [comment]
Yes, but better is to add bower.json for JS packages because here we don't have any PHP files.

**Comment by sprice** [comment]
That's sort of what I was thinking :smile: But instead of bower, why not just use npm? From my experience it does a better job at handling JS packages.

**Comment by ogheo** [comment]
Well, i want to add this plugin to my composer.json file and to update it automatically. To make it available with composer it should be registered on http://bower.io/ or https://packagist.org/. I don't know if the npm does the same thing.

**Comment by ogheo** [comment]
Thanks, you're right, easier is to use it from npm ;)
